from pathlib import Path

from unsloth import FastLanguageModel

from socratic_hint.backends.base import HintBackend
from socratic_hint.output_format import (
    PROMPT_COMPLETION_SEPARATOR,
    format_prompt,
    parse_model_output,
)
from socratic_hint.types import DialogueTurn, HintResult

# Mirrors output_format._FIELD_PREFIXES: lines starting with either terminate
# a hint that runs on for several lines.
_FIELD_PREFIXES = ("state:", "hint:")


class FinetunedBackend(HintBackend):
    def __init__(self, checkpoint_dir: Path, max_seq_length: int = 2048):
        self.model, self.tokenizer = FastLanguageModel.from_pretrained(
            model_name=str(checkpoint_dir),
            max_seq_length=max_seq_length,
            load_in_4bit=True,
        )
        FastLanguageModel.for_inference(self.model)

    def infer_and_hint(
        self,
        dialogue_history: list[DialogueTurn],
        problem: str,
        suppress_state: bool = False,
    ) -> HintResult:
        # The training prompts end with this separator (see
        # `examples_to_hf_dataset`), so appending it here makes the inference
        # context byte-identical to what the model was fine-tuned on. Without
        # it the final token differs (`>` vs the merged `>\n\n`), putting every
        # generation slightly off-distribution.
        prompt = (
            format_prompt(dialogue_history, problem, suppress_state=suppress_state)
            + PROMPT_COMPLETION_SEPARATOR
        )
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)
        output_ids = self.model.generate(**inputs, max_new_tokens=512)
        raw_text = self.tokenizer.decode(
            output_ids[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True
        )
        return parse_model_output(raw_text, suppress_state=suppress_state)

    def infer_hint_given_state(
        self,
        dialogue_history: list[DialogueTurn],
        problem: str,
        injected_state: dict[str, float],
    ) -> str:
        """Generate a hint conditioned on a manually injected state vector,
        bypassing the model's own state self-estimation entirely.

        Training only ever supervises what follows a `State: ...\\n` line, not
        how that line itself is produced, so a `State:` line written into the
        PROMPT (rather than generated by the model) is on-distribution for the
        `Hint:` continuation that follows it. This lets the same-history
        counterfactual adaptivity diagnostic hold the dialogue content fixed
        and vary only the injected state, which the model's own
        self-estimation step (Section 3.4) cannot do on its own, since the
        state and the history it is estimated from are never independent when
        the model produces both itself.
        """
        state_str = ", ".join(f"{k}={v:.2f}" for k, v in injected_state.items())
        prompt = (
            format_prompt(dialogue_history, problem, suppress_state=False)
            + PROMPT_COMPLETION_SEPARATOR
            + f"State: {state_str}\nHint:"
        )
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)
        output_ids = self.model.generate(**inputs, max_new_tokens=512)
        raw_text = self.tokenizer.decode(
            output_ids[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True
        )
        return self._extract_forced_hint(raw_text)

    @staticmethod
    def _extract_forced_hint(continuation: str) -> str:
        """Text generated after a prompt-injected `Hint:` prefix.

        Unlike `parse_model_output`, the `Hint:` label itself is already in
        the prompt, so the continuation starts mid-hint. Collect lines until
        one starts a new field (guards against the model hallucinating a
        trailing `State:`/`Hint:` line of its own).
        """
        lines = continuation.splitlines()
        collected = []
        for line in lines:
            if line.strip().lower().startswith(_FIELD_PREFIXES):
                break
            collected.append(line)
        return "\n".join(collected).strip()
